targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          explicit_to_json: true
          include_if_null: false
      freezed:
        generate_for:
          include:
            - lib/**.dart
        options:
          copy_with: true
          make_collections_unmodifiable: false