name: hand_car
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_list_item: ^1.0.0
  carousel_slider: ^5.0.0
  concentric_transition: ^1.0.3
  dio: ^5.7.0
  fan_carousel_image_slider: ^1.0.1
  equatable: ^2.0.5  # Specify version instead of 'any'
  json_annotation: ^4.9.0
  flutter_gen: ^5.7.0
  flutter_hooks: ^0.20.5
  flutter_onboarding_slider: ^1.0.11
  flutter_otp_text_field: ^1.2.0
  flutter_rating_bar: ^4.0.1
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  image_picker: ^1.1.2
  json_to_dart: ^1.0.5
  lottie: ^3.1.2
  rating_summary: ^1.0.3+1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0
  
  get_storage: ^2.1.1
  shared_preferences: ^2.3.3
  html: ^0.15.5
  badges: ^3.1.2
  panara_dialogs: ^0.1.5
  country_picker: ^2.0.27
  flutter_slidable: ^4.0.0
  font_awesome_flutter: ^10.8.0
  smooth_page_indicator: ^1.2.0+3
  loading_animation_widget: ^1.3.0
  rating_dialog: ^2.0.4
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  dot_navigation_bar: ^1.0.2
  synchronized: ^3.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  riverpod_generator: ^2.4.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.13
  flutter_launcher_icons: ^0.14.1
  mocktail: ^1.0.4
  freezed: ^2.5.7

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/hand_car_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/hand_car_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800